using System.IO;
using System.Windows;
using System.Windows.Markup;
using System.Windows.Media;

namespace HolidayLights.Branding;

/// <summary>
/// Writes <c>src/HolidayLights.App/Assets/Illustrations.xaml</c>: the <c>DrawingImage</c> resources named by
/// <c>AppResourceKeys.Illustration*</c>. The dictionary also merges <c>Tooltips.xaml</c> (the description and tooltip texts),
/// so App.xaml's single merge of this dictionary makes both available everywhere.
/// </summary>
internal static class IllustrationGenerator
{
    /// <summary>The resource keys and what each picture shows (keys: <c>AppResourceKeys</c>).</summary>
    public static readonly (string Key, string Comment, Func<Drawing> Art)[] Illustrations =
    [
        ("HL.Illustration.BehindIcons", "General > Where Bulbs Are Drawn: \"On Desktop, Behind the Icons\" (160 x 96). The bulbs pass under the icons and the window.", () => IllustrationArt.Layer(LayerScene.BehindIcons)),
        ("HL.Illustration.InFrontOfIcons", "\"On Desktop, In Front of the Icons\" (160 x 96). The bulbs cover the icons; the window covers the bulbs.", () => IllustrationArt.Layer(LayerScene.InFrontOfIcons)),
        ("HL.Illustration.OnTop", "\"On Top of All Windows\" (160 x 96). The bulbs cover the icons and the window; the taskbar stays above them.", () => IllustrationArt.Layer(LayerScene.OnTop)),
        ("HL.Illustration.TaskbarCorner.Light", "Welcome card, light mode (320 x 120): the taskbar corner with the ^ flyout open and the red bulb highlighted.", () => IllustrationArt.TaskbarCorner(dark: false)),
        ("HL.Illustration.TaskbarCorner.Dark", "Welcome card, dark mode (320 x 120).", () => IllustrationArt.TaskbarCorner(dark: true)),
    ];

    /// <summary>The file name of the tooltip dictionary merged by the illustrations dictionary.</summary>
    public const string TooltipsFile = "Tooltips.xaml";

    /// <summary>Writes the dictionary and checks that it loads with every key.</summary>
    /// <param name="paths">Repository locations.</param>
    public static void Run(RepoPaths paths)
    {
        string path = Path.Combine(paths.AppAssets, "Illustrations.xaml");
        File.WriteAllText(path, Build(), new System.Text.UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
        ResourceDictionary loaded = Load(path);
        foreach ((string key, _, _) in Illustrations)
        {
            if (loaded[key] is not DrawingImage)
            {
                throw new InvalidOperationException($"{key} did not load as a DrawingImage.");
            }
        }

        Console.WriteLine($"Illustrations written to {path}.");
    }

    /// <summary>Loads the written dictionary (with its merged tooltips) from disk.</summary>
    /// <param name="path">The Illustrations.xaml file.</param>
    /// <returns>The dictionary.</returns>
    public static ResourceDictionary Load(string path)
    {
        using FileStream stream = File.OpenRead(path);
        var context = new ParserContext { BaseUri = new Uri(path, UriKind.Absolute) };
        return (ResourceDictionary)XamlReader.Load(stream, context);
    }

    private static string Build()
    {
        var xaml = new XamlEmitter();
        xaml.Line(0, "<!--");
        xaml.Line(0, "  Vector illustrations (owner: branding-docs). Keys are contracts (AppResourceKeys.Illustration*); App.xaml merges this");
        xaml.Line(0, "  dictionary, which also merges Tooltips.xaml (descriptions and tooltips, PRODUCT-SPEC Appendix A).");
        xaml.Line(0, "  Generated by assets/icons/generator (\"BrandingGenerator illustrations\") from IllustrationArt.cs: change the generator");
        xaml.Line(0, "  and run it again rather than editing the drawings here. Palette: PRODUCT-SPEC 4.2.");
        xaml.Line(0, "-->");
        xaml.Line(0, "<ResourceDictionary xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"");
        xaml.Line(0, "                    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">");
        xaml.Line(0, "");
        xaml.Line(1, "<ResourceDictionary.MergedDictionaries>");
        xaml.Line(2, $"<ResourceDictionary Source=\"{TooltipsFile}\" />");
        xaml.Line(1, "</ResourceDictionary.MergedDictionaries>");
        foreach ((string key, string comment, Func<Drawing> art) in Illustrations)
        {
            xaml.Line(0, "");
            xaml.DrawingImage(1, key, comment, art());
        }

        xaml.Line(0, "");
        xaml.Line(0, "</ResourceDictionary>");
        return xaml.ToString();
    }
}
